version: '2.1'

services:
  movie:
    build: microservices/movie-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  trivia:
    build: microservices/trivia-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: microservices/review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  crazy-credit:
    build: microservices/crazy-credit-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  movie-composite:
    build: microservices/movie-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
