server.port: 7000
server.error.include-message: always

app:
  movie-service:
    host: localhost
    port: 7001
  trivia-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003
  crazy-credit-service:
    host: localhost
    port: 7004

logging:
  level:
    root: INFO
    com.example: DEBUG
    
---
spring.profiles: docker

server.port: 8080

app:
  movie-service:
    host: movie
    port: 8080
  trivia-service:
    host: trivia
    port: 8080
  review-service:
    host: review
    port: 8080
  crazy-credit-service:
    host: crazy-credit
    port: 8080
